//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngilizceKelimeOgreniyorum.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PKLDNBN;Initial Catalog=KelimeOgrenmeDB;Integrated Security=T" +
            "rue")]
        public string KelimeOgrenmeDBConnectionString {
            get {
                return ((string)(this["KelimeOgrenmeDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-9MV313N;Initial Catalog=KelimeOgrenmeDB;Integrated Security=T" +
            "rue")]
        public string KelimeOgrenmeDBConnectionString1 {
            get {
                return ((string)(this["KelimeOgrenmeDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=berkan.database.windows.net;Initial Catalog=KelimeOgrenmeAZUREDB;Pers" +
            "ist Security Info=True;User ID=berkan;Password=7Dr87d7dr")]
        public string KelimeOgrenmeAZUREDBConnectionString {
            get {
                return ((string)(this["KelimeOgrenmeAZUREDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=berkan.database.windows.net;Initial Catalog=KelimeOgrenmeAZUREDB;Pers" +
            "ist Security Info=True;User ID=berkan;Password=7dr87d7dr.")]
        public string KelimeOgrenmeAZUREDBConnectionString1 {
            get {
                return ((string)(this["KelimeOgrenmeAZUREDBConnectionString1"]));
            }
        }
    }
}
