#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngilizceKelimeOgreniyorum
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KelimeOgrenmeAZUREDB")]
	public partial class MyDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Kelime(tbl_Kelime instance);
    partial void Updatetbl_Kelime(tbl_Kelime instance);
    partial void Deletetbl_Kelime(tbl_Kelime instance);
    #endregion
		
		public MyDataClassesDataContext() : 
				base(global::IngilizceKelimeOgreniyorum.Properties.Settings.Default.KelimeOgrenmeAZUREDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<View_SorularıGoruntule> View_SorularıGoruntules
		{
			get
			{
				return this.GetTable<View_SorularıGoruntule>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Kelime> tbl_Kelimes
		{
			get
			{
				return this.GetTable<tbl_Kelime>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSoruSil")]
		public int spSoruSil([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDurumuTestYap")]
		public int spDurumuTestYap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeID", DbType="Int")] System.Nullable<int> kelimeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeOgrenmeDurumu", DbType="NVarChar(50)")] string kelimeOgrenmeDurumu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kelimeID, kelimeOgrenmeDurumu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spKelimeDurumGüncelleOgren")]
		public int spKelimeDurumGüncelleOgren([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeID", DbType="Int")] System.Nullable<int> kelimeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeOgrenmeDurumu", DbType="NVarChar(50)")] string kelimeOgrenmeDurumu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeOgrenmeSeviye", DbType="NVarChar(50)")] string kelimeOgrenmeSeviye, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeTarih", DbType="Date")] System.Nullable<System.DateTime> kelimeTarih)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kelimeID, kelimeOgrenmeDurumu, kelimeOgrenmeSeviye, kelimeTarih);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spKelimeEkle")]
		public int spKelimeEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeTr", DbType="NVarChar(50)")] string kelimeTr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeIng", DbType="NVarChar(50)")] string kelimeIng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeTuru", DbType="NVarChar(50)")] string kelimeTuru, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeOrnek", DbType="NVarChar(50)")] string kelimeOrnek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeOgrenmeDurumu", DbType="NVarChar(50)")] string kelimeOgrenmeDurumu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeOgrenmeSeviyesi", DbType="Int")] System.Nullable<int> kelimeOgrenmeSeviyesi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KelimeOgrenmeTarihi", DbType="DateTime")] System.Nullable<System.DateTime> kelimeOgrenmeTarihi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> kelimeSimdikiTarih)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kelimeTr, kelimeIng, kelimeTuru, kelimeOrnek, kelimeOgrenmeDurumu, kelimeOgrenmeSeviyesi, kelimeOgrenmeTarihi, kelimeSimdikiTarih);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OgrenmeDurumuTestOlanlar")]
		public ISingleResult<OgrenmeDurumuTestOlanlarResult> OgrenmeDurumuTestOlanlar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OgrenmeDurumu", DbType="NVarChar(20)")] string ogrenmeDurumu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ogrenmeDurumu);
			return ((ISingleResult<OgrenmeDurumuTestOlanlarResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_SorularıGoruntule")]
	public partial class View_SorularıGoruntule
	{
		
		private int _KelimeID;
		
		private string _KelimeTR;
		
		private string _KelimeIng;
		
		private string _KelimeTuru;
		
		private string _KelimeOrnek;
		
		private string _KelimeOgrenmeDurumu;
		
		private System.Nullable<int> _KelimeOgrenmeSeviye;
		
		private System.Nullable<System.DateTime> _KelimeOgrenmeTarihi;
		
		public View_SorularıGoruntule()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int KelimeID
		{
			get
			{
				return this._KelimeID;
			}
			set
			{
				if ((this._KelimeID != value))
				{
					this._KelimeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeTR", DbType="NVarChar(50)")]
		public string KelimeTR
		{
			get
			{
				return this._KelimeTR;
			}
			set
			{
				if ((this._KelimeTR != value))
				{
					this._KelimeTR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeIng", DbType="NVarChar(50)")]
		public string KelimeIng
		{
			get
			{
				return this._KelimeIng;
			}
			set
			{
				if ((this._KelimeIng != value))
				{
					this._KelimeIng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeTuru", DbType="NVarChar(50)")]
		public string KelimeTuru
		{
			get
			{
				return this._KelimeTuru;
			}
			set
			{
				if ((this._KelimeTuru != value))
				{
					this._KelimeTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOrnek", DbType="NVarChar(50)")]
		public string KelimeOrnek
		{
			get
			{
				return this._KelimeOrnek;
			}
			set
			{
				if ((this._KelimeOrnek != value))
				{
					this._KelimeOrnek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeDurumu", DbType="NVarChar(50)")]
		public string KelimeOgrenmeDurumu
		{
			get
			{
				return this._KelimeOgrenmeDurumu;
			}
			set
			{
				if ((this._KelimeOgrenmeDurumu != value))
				{
					this._KelimeOgrenmeDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeSeviye", DbType="Int")]
		public System.Nullable<int> KelimeOgrenmeSeviye
		{
			get
			{
				return this._KelimeOgrenmeSeviye;
			}
			set
			{
				if ((this._KelimeOgrenmeSeviye != value))
				{
					this._KelimeOgrenmeSeviye = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> KelimeOgrenmeTarihi
		{
			get
			{
				return this._KelimeOgrenmeTarihi;
			}
			set
			{
				if ((this._KelimeOgrenmeTarihi != value))
				{
					this._KelimeOgrenmeTarihi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Kelime")]
	public partial class tbl_Kelime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KelimeID;
		
		private string _KelimeTR;
		
		private string _KelimeIng;
		
		private string _KelimeTuru;
		
		private string _KelimeOrnek;
		
		private string _KelimeOgrenmeDurumu;
		
		private System.Nullable<int> _KelimeOgrenmeSeviye;
		
		private System.Nullable<System.DateTime> _KelimeOgrenmeTarihi;
		
		private System.Nullable<System.DateTime> _KelimeSimdikiTarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKelimeIDChanging(int value);
    partial void OnKelimeIDChanged();
    partial void OnKelimeTRChanging(string value);
    partial void OnKelimeTRChanged();
    partial void OnKelimeIngChanging(string value);
    partial void OnKelimeIngChanged();
    partial void OnKelimeTuruChanging(string value);
    partial void OnKelimeTuruChanged();
    partial void OnKelimeOrnekChanging(string value);
    partial void OnKelimeOrnekChanged();
    partial void OnKelimeOgrenmeDurumuChanging(string value);
    partial void OnKelimeOgrenmeDurumuChanged();
    partial void OnKelimeOgrenmeSeviyeChanging(System.Nullable<int> value);
    partial void OnKelimeOgrenmeSeviyeChanged();
    partial void OnKelimeOgrenmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnKelimeOgrenmeTarihiChanged();
    partial void OnKelimeSimdikiTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnKelimeSimdikiTarihChanged();
    #endregion
		
		public tbl_Kelime()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KelimeID
		{
			get
			{
				return this._KelimeID;
			}
			set
			{
				if ((this._KelimeID != value))
				{
					this.OnKelimeIDChanging(value);
					this.SendPropertyChanging();
					this._KelimeID = value;
					this.SendPropertyChanged("KelimeID");
					this.OnKelimeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeTR", DbType="NVarChar(50)")]
		public string KelimeTR
		{
			get
			{
				return this._KelimeTR;
			}
			set
			{
				if ((this._KelimeTR != value))
				{
					this.OnKelimeTRChanging(value);
					this.SendPropertyChanging();
					this._KelimeTR = value;
					this.SendPropertyChanged("KelimeTR");
					this.OnKelimeTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeIng", DbType="NVarChar(50)")]
		public string KelimeIng
		{
			get
			{
				return this._KelimeIng;
			}
			set
			{
				if ((this._KelimeIng != value))
				{
					this.OnKelimeIngChanging(value);
					this.SendPropertyChanging();
					this._KelimeIng = value;
					this.SendPropertyChanged("KelimeIng");
					this.OnKelimeIngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeTuru", DbType="NVarChar(50)")]
		public string KelimeTuru
		{
			get
			{
				return this._KelimeTuru;
			}
			set
			{
				if ((this._KelimeTuru != value))
				{
					this.OnKelimeTuruChanging(value);
					this.SendPropertyChanging();
					this._KelimeTuru = value;
					this.SendPropertyChanged("KelimeTuru");
					this.OnKelimeTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOrnek", DbType="NVarChar(50)")]
		public string KelimeOrnek
		{
			get
			{
				return this._KelimeOrnek;
			}
			set
			{
				if ((this._KelimeOrnek != value))
				{
					this.OnKelimeOrnekChanging(value);
					this.SendPropertyChanging();
					this._KelimeOrnek = value;
					this.SendPropertyChanged("KelimeOrnek");
					this.OnKelimeOrnekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeDurumu", DbType="NVarChar(50)")]
		public string KelimeOgrenmeDurumu
		{
			get
			{
				return this._KelimeOgrenmeDurumu;
			}
			set
			{
				if ((this._KelimeOgrenmeDurumu != value))
				{
					this.OnKelimeOgrenmeDurumuChanging(value);
					this.SendPropertyChanging();
					this._KelimeOgrenmeDurumu = value;
					this.SendPropertyChanged("KelimeOgrenmeDurumu");
					this.OnKelimeOgrenmeDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeSeviye", DbType="Int")]
		public System.Nullable<int> KelimeOgrenmeSeviye
		{
			get
			{
				return this._KelimeOgrenmeSeviye;
			}
			set
			{
				if ((this._KelimeOgrenmeSeviye != value))
				{
					this.OnKelimeOgrenmeSeviyeChanging(value);
					this.SendPropertyChanging();
					this._KelimeOgrenmeSeviye = value;
					this.SendPropertyChanged("KelimeOgrenmeSeviye");
					this.OnKelimeOgrenmeSeviyeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> KelimeOgrenmeTarihi
		{
			get
			{
				return this._KelimeOgrenmeTarihi;
			}
			set
			{
				if ((this._KelimeOgrenmeTarihi != value))
				{
					this.OnKelimeOgrenmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._KelimeOgrenmeTarihi = value;
					this.SendPropertyChanged("KelimeOgrenmeTarihi");
					this.OnKelimeOgrenmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeSimdikiTarih", DbType="Date")]
		public System.Nullable<System.DateTime> KelimeSimdikiTarih
		{
			get
			{
				return this._KelimeSimdikiTarih;
			}
			set
			{
				if ((this._KelimeSimdikiTarih != value))
				{
					this.OnKelimeSimdikiTarihChanging(value);
					this.SendPropertyChanging();
					this._KelimeSimdikiTarih = value;
					this.SendPropertyChanged("KelimeSimdikiTarih");
					this.OnKelimeSimdikiTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class OgrenmeDurumuTestOlanlarResult
	{
		
		private int _KelimeID;
		
		private string _KelimeTR;
		
		private string _KelimeIng;
		
		private string _KelimeTuru;
		
		private string _KelimeOrnek;
		
		private string _KelimeOgrenmeDurumu;
		
		private System.Nullable<int> _KelimeOgrenmeSeviye;
		
		private System.Nullable<System.DateTime> _KelimeOgrenmeTarihi;
		
		private System.Nullable<System.DateTime> _KelimeSimdikiTarih;
		
		public OgrenmeDurumuTestOlanlarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeID", DbType="Int NOT NULL")]
		public int KelimeID
		{
			get
			{
				return this._KelimeID;
			}
			set
			{
				if ((this._KelimeID != value))
				{
					this._KelimeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeTR", DbType="NVarChar(50)")]
		public string KelimeTR
		{
			get
			{
				return this._KelimeTR;
			}
			set
			{
				if ((this._KelimeTR != value))
				{
					this._KelimeTR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeIng", DbType="NVarChar(50)")]
		public string KelimeIng
		{
			get
			{
				return this._KelimeIng;
			}
			set
			{
				if ((this._KelimeIng != value))
				{
					this._KelimeIng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeTuru", DbType="NVarChar(50)")]
		public string KelimeTuru
		{
			get
			{
				return this._KelimeTuru;
			}
			set
			{
				if ((this._KelimeTuru != value))
				{
					this._KelimeTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOrnek", DbType="NVarChar(50)")]
		public string KelimeOrnek
		{
			get
			{
				return this._KelimeOrnek;
			}
			set
			{
				if ((this._KelimeOrnek != value))
				{
					this._KelimeOrnek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeDurumu", DbType="NVarChar(50)")]
		public string KelimeOgrenmeDurumu
		{
			get
			{
				return this._KelimeOgrenmeDurumu;
			}
			set
			{
				if ((this._KelimeOgrenmeDurumu != value))
				{
					this._KelimeOgrenmeDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeSeviye", DbType="Int")]
		public System.Nullable<int> KelimeOgrenmeSeviye
		{
			get
			{
				return this._KelimeOgrenmeSeviye;
			}
			set
			{
				if ((this._KelimeOgrenmeSeviye != value))
				{
					this._KelimeOgrenmeSeviye = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeOgrenmeTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> KelimeOgrenmeTarihi
		{
			get
			{
				return this._KelimeOgrenmeTarihi;
			}
			set
			{
				if ((this._KelimeOgrenmeTarihi != value))
				{
					this._KelimeOgrenmeTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KelimeSimdikiTarih", DbType="Date")]
		public System.Nullable<System.DateTime> KelimeSimdikiTarih
		{
			get
			{
				return this._KelimeSimdikiTarih;
			}
			set
			{
				if ((this._KelimeSimdikiTarih != value))
				{
					this._KelimeSimdikiTarih = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
